project:
  type: website
  output-dir: docs

website:
  title: "Fidèle Balume"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - links.qmd
      - posts.qmd

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

