---
title: "About"
---

Welcome to my personal website!

I am currently a PhD candidate. I'm preparing a thesis in Corporate Finance and I'm working on the bankruptcy costs associated with LBO companies in financial distress. At the same time, I gained teaching experience in Finance, Accounting and Controlling.

Through my research work, I try to contribute to the advancement of knowledge in Corporate Finance and provide solutions to current challenges in order to "count what really matters".

Here you'll find information on my courses, research projects and publications, as well as some important resources for furthering your knowledge.

On my blog, you'll find some insightful posts on subjects of interest to me. You'll also find feedback on the research activities I've carried out (including abroad visiting). Whether they're about major career steps or visits abroad, I'll do my best to share with you not only the facts and key moments of the adventure, but also the emotions, reflections and moments of doubt that accompanied it. My aim is to share my experience with you as accurately as possible.

I hope you'll find some good ideas and inspiration on the site. Please don't hesitate to contact me if you have any questions, suggestions or proposals for collaboration.

Enjoy your visit!
