---
title: "Research and Academic activities"
editor: visual
---

# Publications and conferences

## Publications

[Balume, F., (2024). Fonds Vautours, Coûts Cognitifs et Faillite des LBO, *Finance Contrôle Stratégie*, (Vol. 27 No. 2)](https://journals.openedition.org/fcs/12793)

[Balume, F., (2024). Vulture Funds, Cognitive Cost and LBO Bankruptcy. *Finance Contrôle Stratégie*, (Vol. 27 No. 2)](https://journals.openedition.org/fcs/12700)

[Balume, F., Gajewski, J. F., & Heimann, M. (2024). Cognitive Load, Social Values, and Financial Distress: Drivers of Restructuring Decisions. *Review of Accounting and Finance*, (Vol. 23 No. 4, pp. 506-536).](https://www.emerald.com/insight/content/doi/10.1108/RAF-07-2023-0212/full/html)

## Conferences

Balume, F., Gajewski, J. F., & King, DT. (2024). *LBO and Firm ESG Commitment*. In *18th National Yang-Ming Chiao Tung University (NYCU) International Finance Conference*.

Balume, F., Gajewski, J. F., & King, DT. (2024). *The Effect of the LBO Deal On The Firm’s ESG Commitment ?*. In[ *40th International Conference of the French Financial Association (AFFI)*.](https://affi2024.eventsadmin.com/i/Program)

Balume, F., Gajewski, J. F., & King, DT. (2024). *Does the LBO Deal Affect the Firm’s ESG Commitment in Financial Distress Situation ?*. In *2024 Clermont Financial Innovation Workshop (CFIW24).*

Balume, F., Gajewski, J. F., & King, DT. (2024). *Does the LBO Deal Affect the Firm’s ESG Commitment in Financial Distress Situation ?*. In *In 3rd Investor Emotions & Asset Pricing Conference (IEAP)*.

Balume, F., Gajewski, J. F., & Heimann, M. (2023). *Managerial Preferences in Financial Distress: The Role of Cognitive Load and Social Value Orientation in Restructuring Decisions*. In *39th International Conference of the French Financial Association (AFFI)*.

Balume, F., Gajewski, J. F., & Heimann, M. (2023). *Managerial Preferences in Financial Distress: The Role of Cognitive Load and Social Value Orientation in Restructuring Decisions*. In *12th International Conference of the Financial Engineering and Banking Society (FEBS)*.

Balume, F., Gajewski, J. F., & Heimann, M. (2023). *Managers internal factors and LBO restructuring decision-making. In 2023 Clermont Financial Innovation Workshop (CFIW23).*

Balume, F., Gajewski, J. F., & Heimann, M. (2023). *Managers internal factors and LBO restructuring decision-making. In 2nd Investor Emotions & Asset Pricing Conference (IEAP).*

Balume, F., (2022). *The Cognitive Load Impact on Managers’ Rationality and the Moderating Effect of Being ‘Social Value Oriented’: An Experimental Study. Corporate Behavioral Finance Summer School, Aarhus University (AU Denmark).*

# Teachings

### Financements structurés (S8)

### Finance (S6)
###### Détermination d'une clé de contrôle ISIN : [Clé de contrôle ISIN - Fichier Excel](CléContrôleISIN.xlsx)

### Fondamentaux de la finance (S5)

###### Choix d'investissement : [Modèle FTN, VAN, TRI & IP - Fichier Excel](ModèleChoixInvestissement.xlsx)

### Contrôle de gestion (S3)

### Gestion comptable 1 (S1)

### Gestion comptable 2 (S2)
