---
title: "indexFrench"
format: html
draft: true # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

Dans cet article de presse, je voudrais aborder la question des fonds spéculatifs identifiés par les chercheurs en finance et en économie comme une catégorie spécifique de fonds appelés « fonds vautours » (FV). Il s'agit de fonds d'investissement dont l'activité est comparable à celle des vautours vis-à-vis des entreprises en difficulté, voire des gouvernements. Ces fonds opèrent en contexte de faillite, car ces périodes de difficultés financières sont propices à l'achat par les fonds vautours de la dette décotée des entreprises, qu'ils utilisent ensuite comme levier pour une stratégie de « loan-to-own » (prêt pour acquérir) ou de « yield chasing » (recherche de rendement). Les recherches portant sur ce sujet se sont presque exclusivement concentrées sur l'impact de ces fonds sur les gouvernements (hormis Hotchkiss et Moradian, 1997 ; Gietzmann, 2018). Dans mon étude publiée dans la revue *Finance-Contrôle-Stratégie* (2024), je réalise une exploration approfondie de l'impact de l'activité des fonds vautours sur le processus de faillite de deux entreprises rachetées auparavant avec effet de levier (LBO): Vivarte et de Camaïeu. J'observe que ces fonds cherchent généralement à maximiser leurs rendements en employant diverses stratégies agressives (légales et illégales), et que les activités de ces fonds peuvent aggraver les difficultés financières de l'entreprise, complexifier la prise de décision managériale et empêcher une prise de décision efficiente. Cela s'explique notamment par des coûts cognitifs résiduels engendrés par les activités des fonds vautours au cours de la période de difficultés financières.